entities:
  - name: Consultant  # Resource table
    rows: 30 # resource table must have fixed number of rows
    attributes:
      - name: id
        type: pk
      - name: name
        type: string
        generator:
          type: faker
          method: name
      - name: email
        type: string
        generator:
          type: faker
          method: email
      - name: role 
        type: resource_type # Column referenced by resource_type in sim config
        generator:
          type: distribution
          distribution:
            type: choice
            values: ["Developer", "Tester", "Tech Lead", "Business Analyst"]
            weights: [0.5, 0.2, 0.2, 0.1]  # Distribution of resource types

  - name: Project
    rows: n/a
    attributes:
      - name: id
        type: pk
      - name: name
        type: string
        generator:
          type: template 
          template: "Project_{id}"

  - name: Deliverable  # Event table
    rows: n/a
    attributes:
      - name: id
        type: pk
      - name: project_id
        type: fk
        ref: Project.id
        relationship:
          type: one_to_many
          multiplicity:
            distribution:
              type: normal
              mean: 4
              stddev: 1
              min: 2
              max: 8
      - name: name
        type: string
        generator:
          type: template
          template: "Deliverable_{id}"
      - name: type
        type: event_type # Column referenced by event_type in sim config
        generator:
          type: simulation_event
          values: ["Requirements", "Design", "Implementation", "Testing", "Deployment"]

# Key Concepts:
# 1. type/role columns define different entity/resource types that are matched
#    in the simulation config
# 2. Distributions and weights help create realistic test data
# 3. All datetime generation is controlled by simulation timing config