entities:
  - name: Consultant  # Resource table
    rows: 20 # resource table must have fixed number of rows
    attributes:
      - name: id
        type: pk     # Primary key for resource identification
      - name: name
        type: string
        generator:
          type: faker      # Uses Faker library for realistic data
          method: name
      - name: email
        type: string
        generator:
          type: faker
          method: email
      - name: role        # Column referenced by resource_type in sim config
        type: string
        generator:
          type: distribution
          distribution:
            type: choice
            values: ["Developer", "Tester", "Tech Lead"]
            weights: [0.6, 0.2, 0.2]  # Distribution of resource types

  - name: Project    # Parent table for deliverables
    rows: 5  # Generate 5 projects for testing FK distribution
    attributes:
      - name: id
        type: pk
      - name: name
        type: string
        generator:
          type: template    # Simple sequential naming
          template: "Project_{id}"

  - name: Deliverable  # Entity table
    rows: 10  # Generate 10 deliverables
    attributes:
      - name: id
        type: pk
      - name: project_id
        type: fk          # Foreign key to parent project
        ref: Project.id
        generator:
          type: distribution  # Define how deliverables are distributed across projects
          distribution:
            type: choice
            mode: parent_id  # Special mode to indicate this is for FK distribution
            weights: [0.4, 0.3, 0.2, 0.05, 0.05]  # Weights for each project (must match number of parent records)
      - name: name
        type: string
        generator:
          type: template
          template: "Deliverable_{id}"
      - name: type      # Column referenced by entity_type in sim config
        type: string
        generator:
          type: distribution
          distribution:
            type: choice
            values: ["Design", "Coding", "Testing"]
            weights: [0.3, 0.4, 0.3]
            simulation_override: true  # Indicates this distribution can be overridden by simulation

# Key Concepts:
# 1. type/role columns define different entity/resource types that are matched
#    in the simulation config
# 2. Distributions and weights help create realistic test data
# 3. All datetime generation is controlled by simulation timing config