process:
  name: coding_development
  description: "Software coding phase"
  
  entity_table:
    parent_table:
      name: Project
      type_column: id

    child_table:
      name: Deliverable
      type_column: type
      relationship: project_id
      arrival_pattern:
        delay: 0
        count:
          distribution:
            type: normal
            mean: 2
            std: 1

  resource_table:
    name: Consultant
    type_column: role

  requirements:
    - entity_type: "Coding"
      needs:
        - resource_type: "Developer"
          quantity: 1

  duration:
    distribution:
      type: normal
      mean: 5
      std: 1