process:
  name: design_development
  description: "Software design phase"
  
  entity_table:
    parent_table:
      name: Project
      type_column: id
      arrival_pattern:
        type: poisson
        rate: 0.2  # New projects arrive every 5 days on average

    child_table:
      name: Deliverable
      type_column: type
      relationship: project_id
      arrival_pattern:
        delay: 0  # Immediate after project creation
        count: 1  # One design deliverable per project

  resource_table:
    name: Consultant
    type_column: role

  requirements:
    - entity_type: "Design"
      needs:
        - resource_type: "Tech Lead"
          quantity: 1

  duration:
    distribution:
      type: normal
      mean: 3
      std: 1