# Event-based simulation configuration
simulation:
  duration_days: 90
  start_date: 2024-02-01
  random_seed: 42

# Event simulation configuration
event_simulation:
  # The parent entity table
  entity_table: Project
  
  # Entity arrival pattern configuration
  entity_arrival:
    # Distribution for time between entity arrivals (in days)
    interarrival_time:
      distribution:
        type: exponential
        scale: 15
        min: 
    
    # Optional: Maximum number of entities to generate (if null, determined by simulation duration)
    max_entities: null
    # Whether to override any row count in the database configuration
    override_db_config: true
  
  event_table: Deliverable
  relationship_column: project_id
  
  # Distribution configuration for event duration
  event_duration:
    distribution:
      type: normal
      mean: 5
      stddev: 1
      min: 1
      max: 10
  
  # Work shift configuration
  work_shifts:
    enabled: false
    shift_patterns:
      - name: "Regular Weekday"
        days: [0, 1, 2, 3, 4]  # Monday to Friday (0=Monday)
        start_time: "07:00"
        end_time: "19:00"
      - name: "Weekend Support"
        days: [5, 6]  # Saturday and Sunday
        start_time: "08:00"
        end_time: "20:00"
      - name: "Evening Shift"
        days: [0, 1, 2, 3, 4]  # Monday to Friday
        start_time: "15:00"
        end_time: "01:00"
      - name: "24/7 Support"
        days: [0, 1, 2, 3, 4, 5, 6]  # All days
        start_time: "00:00"
        end_time: "23:59"
    
    # Resource shift assignments
    resource_shifts:
      - resource_type: "Developer"
        shift_patterns: ["Regular Weekday", "Weekend Support", "Evening Shift"]
      - resource_type: "Tech Lead"
        shift_patterns: ["Regular Weekday", "Evening Shift", "24/7 Support"]
      - resource_type: "Tester"
        shift_patterns: ["Regular Weekday", "Weekend Support", "Evening Shift", "24/7 Support"]
  
  # Resource requirements for each events
  resource_requirements:
    - resource_table: Consultant
      type_column: role
      requirements:
        - resource_type: Developer
          # Distribution-based resource count
          count:
            distribution:
              type: normal
              mean: 5
              stddev: 0.5
              min: 3
              max: 8
              
        - resource_type: Tech Lead
          # Fixed count
          count: 1
          
        - resource_type: Tester
          count:
            distribution:
              type: uniform
              min: 1
              max: 3