entities:
  - name: Client
    attributes:
      - name: id
        type: int
      - name: name
        type: string
        generator:
          type: faker
          method: name

  - name: Project
    attributes:
      - name: id
        type: int
      - name: name
        type: string
        generator:
          type: faker
          method: sentence
          nb_words: 6
      - name: assigned_client
        type: int
        foreign_key: Client.id

relationships:
  - from: Project
    to: Client

initial_population:
  Client:
    count: 10
  Project:
    count: 20

events:
  - name: AssignProjectToClient
    type: Assign
    entity: Project
    params:
      relationship: assigned_client
      assign_to: 
        distribution: uniform
        min: 1
        max: 10

simulation_parameters:
  duration: 30
  time_unit: day