entities:
  - name: Client
    attributes:
      - name: id
        type: int
      - name: name
        type: string
        generator:
          type: faker
          method: name

  - name: Project
    attributes:
      - name: id
        type: int
      - name: name
        type: string
        generator:
          type: faker
          method: sentence
          nb_words: 6
      - name: assigned_client
        type: int
        foreign_key: Client.id
      - name: CreatedAt
        type: datetime

relationships:
  - from: Project
    to: Client
    type: one_to_many

initial_population:
  Client:
    count: 10
    # Use uniform distribution for creation times
    creation_time_distribution: UNIF(0, 720)
  Project:
    count: 20
    creation_time_distribution: UNIF(0, 720)

events:
  - name: AssignProjectToClient
    type: Assign
    entity: Project
    params:
      relationship_field: assigned_client
      # Assign based on uniform distribution from available client IDs
      assign_to: UNIF(1, 11)  # 11 is exclusive

simulation_parameters:
  start_date: "2023-01-01 00:00:00"
  end_date: "2023-02-01 00:00:00"
  time_unit: day
  work_schedule:
    hours_per_day: 8
    start_hour: 9
    end_hour: 17
    work_days: [1, 2, 3, 4, 5]