entities:
  - name: Client
    attributes:
      - name: id
        type: int
      - name: name
        type: string
        generator:
          type: faker
          method: name

  - name: Project
    attributes:
      - name: id
        type: int
      - name: name
        type: string
        generator:
          type: faker
          method: sentence
          nb_words: 6
      - name: assigned_client
        type: int
        foreign_key: Client.id
      - name: CreatedAt
        type: datetime

relationships:
  - from: Project
    to: Client

initial_population:
  Client:
    count: 10
    creation_time_distribution:
      type: uniform
  Project:
    count: 20
    creation_time_distribution:
      type: uniform

events:
  - name: AssignProjectToClient
    type: Assign
    entity: Project
    params:
      relationship: assigned_client
      assign_to: 
        distribution: uniform
        min: 1
        max: 10
    delay:
      distribution: uniform
      min: 1
      max: 5  # days

simulation_parameters:
  start_date: "2023-01-01 00:00:00"
  end_date: "2023-02-01 00:00:00"
  time_unit: day