# Configuration Schema
entities:  # Required(R), at least one entity
  - name: str  # R, unique
    type: str  # R, one of: ["resource", "process_entity"]
    initial_population:  # Optional, default=0
      count: int  # R if initial_population specified
    attributes:  # R, at least one attribute
      - name: str   # R, unique within entity
        type: str   # R, one of: ["int", "float", "string", "datetime", "boolean"]
        primary_key: bool  # Optional, default=false
        nullable: bool     # Optional, default=false
        generator:  # Optional
          type: str  # R if generator specified, one of:
                    # ["faker", "distribution", "template", "same_as", "choice"]
          # For faker:
          method: str  # R for faker, valid faker method name
          
          # For distribution:
          distribution: str  # R for distribution, formats:
                           # UNIF(min,max) - Uniform
                           # NORM(mean,std) - Normal
                           # DISC(p1,p2,...) - Discrete
                           # TRIA(min,mode,max) - Triangular ... and more
          choices: list[str]  # R for discrete distributions
          
          # For template:
          template: str  # R for template, e.g., "Project_{id}"
          
          # For same_as:
          field: str    # R for same_as, reference field name
          
          # For choice:
          choices: list[str]  # R for choice
          weights: list[float]  # Optional for choice

resource_definitions:  # R if using resource entities
  - table: str  # R, must match a resource entity name
    type_field: str  # R, must match an attribute name

relationships:  # Optional
  - from: str  # R, must match an entity name
    to: str    # R, must match
    type: str  # R, one of: ["one_to_one", "one_to_many", "many_to_many"]
    mapping_table: str  # R for many_to_many relationship
    
events:  # R for process entities
  - name: str  # R, unique
    type: str  # R, one of: ["Process"]
    entity: str  # R, must match a process_entity name
    process_config:  # R for Process type
      duration: str  # R, distribution format
      R_resources:  # R
        - type: str   # R, must match a resource type
          count: int  # R, > 0

simulation_parameters:  # R
  start_date: str  # R, format: "YYYY-MM-DD HH:MM:SS"
  end_date: str    # R, all dates follows the same format
  time_unit: str   # R, one of: ["minute", "hour", "day"]
  work_schedule:   # R
    hours_per_day: int  # R, range: 1-24
    start_hour: int     # R, range: 0-23
    end_hour: int       # R, range: 1-24, must be > start_hour
    work_days: list[int]  # R, range: 1-7 (Monday=1)