# Configuration Schema
entities:  # Required(R), at least one entity
  - name: str  # R, unique
    type: str  # R, one of: ["resource", "process_entity"]
    attributes:  # R, at least one attribute
      - name: str   # R, unique within entity
        type: str   # R, one of: ["int", "float", "string", "datetime", "boolean"]
        primary_key: bool  # Optional, default=false
        nullable: bool     # Optional, default=false
        generator:  # Optional
          type: str  # R if generator specified, one of:
                    # ["faker", "distribution", "template", "same_as", "choice"]
          # For faker:
          method: str  # R for faker, valid faker method name
          
          # For distribution:
          distribution: str  # R for distribution, formats:
                           # UNIF(min,max) - Uniform
                           # NORM(mean,std) - Normal
                           # DISC(p1,p2,...) - Discrete
                           # TRIA(min,mode,max) - Triangular
                           # EXPO(mean) - Exponential
                           # POIS(mean) - Poisson
                           # CONS(value) - Constant
          choices: list[str]  # R for discrete distributions
          
          # For template:
          template: str  # R for template, e.g., "Project_{id}"
          
          # For same_as:
          field: str    # R for same_as, reference field name
          
          # For choice:
          choices: list[str]  # R for choice
          weights: list[float]  # Optional for choice

resource_definitions:  # R if using resource entities
  - table: str  # R, must match a resource entity name
    type_field: str  # R, must match an attribute name

relationships:  # Optional
  - from: str  # R, must match an entity name
    to: str    # R, must match
    type: str  # R, one of: ["one_to_one", "one_to_many", "many_to_many"]
    mapping_table: str  # R for many_to_many relationship
    
events:  # R for process entities
  - name: str  # R, unique
    type: str  # R, one of: ["Process"]
    entity: str  # R, must match a process_entity name
    process_config:  # R for Process type
      duration: str  # R, distribution format
      required_resources:  # R
        - resource_table: str  # R, must match a resource entity name
          type: str   # R, must match a resource type
          count: int  # R, > 0
      dependencies:  # Optional, list of event dependencies
        - event: str  # R, must match another event name
          type: str   # R, one of: ["finish_to_start", "start_to_start", 
                     #             "finish_to_finish", "start_to_finish"]
          delay: str  # Optional, distribution format for additional delay
      follow_up:  # Optional, list of events to schedule after completion
        - event: str  # R, must match another event name
          delay: str  # Optional, distribution format for delay
          params: dict  # Optional, parameters to pass to follow-up event

initial_population:  # R
  "entity_name":  # R, must match an entity name
    count: int    # R, initial population size

simulation_parameters:  # R
  start_date: str  # R, format: "YYYY-MM-DD HH:MM:SS"
  end_date: str    # R, same format as start_date
  time_unit: str   # R, one of: ["minute", "hour", "day"]
  work_schedule:   # R
    hours_per_day: int  # R, range: 1-24
    start_hour: int     # R, range: 0-23
    end_hour: int       # R, range: 1-24, must be > start_hour
    work_days: list[int]  # R, range: 1-7 (Monday=1)
  parallel_limit: int  # Optional, max parallel processes per entity. In Progress
  queue_strategy: str  # Optional, one of: ["FIFO", "LIFO", "PRIORITY"]. In Progress
  resource_allocation: str  # Optional, one of: ["random", "least_utilized", "most_skilled"]