entities:
  - name: Consultant
    type: resource
    attributes:
      - name: id
        type: int
      - name: CreatedAt
        type: datetime
        generator:
          type: distribution
          distribution: UNIF()
      - name: name
        type: string
        generator:
          type: faker
          method: name
      - name: email
        type: string
        generator:
          type: faker
          method: email
      - name: role
        type: string
        generator:
          type: distribution
          distribution: DISC(0.6, 0.2, 0.2)
          choices:
            - "Developer"
            - "Tester"
            - "Tech Lead"

  - name: Project
    type: process_entity
    attributes:
      - name: id
        type: int
      - name: CreatedAt
        type: datetime
        generator:
          type: distribution
          distribution: UNIF()
      - name: name
        type: string
        generator:
          type: template
          template: "Project_{id}"
      - name: start_date
        type: datetime
        generator:
          type: same_as
          field: CreatedAt
      - name: end_date
        type: datetime
        nullable: true

relationships:
  - from: Project
    to: Consultant
    type: many_to_many
    mapping_table: Project_Consultant_Process

initial_population:
  Consultant:
    count: 50
  Project:
    count: 10

resource_definitions:
  - table: Consultant
    type_field: role

events:
  - name: "Front Page Redesign"
    type: "Process"
    entity: "Project"
    process_config:
      duration: NORM(40, 10)
      required_resources:
        - resource_table: "Consultant"
          type: "Tech Lead"
          count: 1
        - resource_table: "Consultant"
          type: "Developer"
          count: 1
      dependencies: []  # No dependencies for first event

  - name: "Development"
    type: "Process"
    entity: "Project"
    process_config:
      duration: NORM(100, 20)
      required_resources:
        - resource_table: "Consultant"
          type: "Developer"
          count: 2
      dependencies:
        - event: "Front Page Redesign"
          type: "finish_to_start"

  - name: "Testing"
    type: "Process"
    entity: "Project"
    process_config:
      duration: NORM(50, 10)
      required_resources:
        - resource_table: "Consultant"
          type: "Tester"
          count: 2
      dependencies:
        - event: "Development"
          type: "finish_to_start"

simulation_parameters:
  start_date: "2023-01-01 00:00:00"
  end_date: "2023-03-01 00:00:00"
  time_unit: day
  work_schedule:
    hours_per_day: 8
    start_hour: 9
    end_hour: 17
    work_days: [1, 2, 3, 4, 5]