simulation:
  # Basic simulation parameters
  duration: 30  # Length of simulation run in days
  time_unit: days  # Base unit for all time calculations
  random_seed: 42  # For reproducible results
  timing:
    # Global simulation timeframe - used by all arrival processes
    start_time: "2024-01-01"  # All created_at times will be generated between these
    end_time: "2024-01-30"    # two dates based on arrival patterns

processes:
  # Each process represents a seize-delay-release pattern in discrete event simulation
  - name: deliverable_assignment
    description: "Process of assigning consultants to deliverables"
    
    # Maps simulation entities to database tables
    entity_table: Deliverable    # Table containing entities to be processed
    resource_table: Consultant   # Table containing resources that process entities
    
    # Defines how to identify different types of entities in the database
    entity_type:
      column: type  # Column name in entity_table that defines entity type
      values: ["Design", "Coding", "Testing"]  # All possible entity types
    
    # Defines how to identify different types of resources in the database
    resource_type:
      column: role  # Column name in resource_table that defines resource type
      values: ["Tech Lead", "Developer", "Tester"]  # All possible resource types
    
    # Maps which types of resources are needed for each entity type
    # Similar to Arena's resource requirements definition
    requirements:
      - entity_type: "Design"
        needs:
          - resource_type: "Tech Lead"
            quantity: 1  # Number of resources needed
      
      - entity_type: "Coding"
        needs:
          - resource_type: "Developer"
            quantity: 1
      
      - entity_type: "Testing"
        needs:
          - resource_type: "Tester"
            quantity: 1
    
    # Duration of the process once resources are seized
    duration:
      distribution:
        type: normal
        mean: 5   # Average processing time
        std: 1    # Standard deviation of processing time
    
    # Resource capacity constraints
    capacity:
      max_concurrent: 3  # Maximum number of tasks a resource can handle simultaneously

metrics:
  - name: assignment_duration
    description: "Time taken to complete deliverable assignment"
    type: duration
    unit: days
    
  - name: resource_utilization
    description: "Consultant utilization rate"
    type: percentage
    aggregation: average
    
  - name: waiting_time
    description: "Time deliverable waited for consultant assignment"
    type: duration
    unit: hours

# Note: The simulation engine will automatically create a mapping table
# containing: entity_id, resource_id, start_time, end_time, duration, status
