entities:
  - name: Order
    attributes:
      - name: id
        type: int
        primary_key: true
      - name: customer_name
        type: string
        generator: 
          type: faker
          method: name
      - name: status
        type: string
        choices: [Pending, Processing, Shipped, Delivered]
      - name: total_amount
        type: float
        generator:
          type: uniform
          min: 10
          max: 1000

  - name: Employee
    attributes:
      - name: id
        type: int
        primary_key: true
      - name: name
        type: string
        generator:
          type: faker
          method: name
      - name: role
        type: string
        choices: [Manager, Worker]

events:
  - name: CreateOrder
    type: Create
    entity: Order
    frequency:
      distribution: poisson
      lambda: 5
    follow_up:
      - event: AssignOrder
        delay:
          distribution: exponential
          mean: 1

  - name: AssignOrder
    type: Assign
    entity: Order
    action:
      relationship: assigned_employee
      assign_to: Employee
      where: "role == 'Worker'"
    follow_up:
      - event: UpdateOrderStatus
        delay:
          distribution: uniform
          min: 1
          max: 3

  - name: UpdateOrderStatus
    type: Update
    entity: Order
    action:
      set:
        status: Processing

simulation_parameters:
  duration: 30
  time_unit: days
  random_seed: 42

initial_population:
  Order:
    count: 0
  Employee:
    count: 10
    attributes:
      role:
        distribution: choice
        choices: [Manager, Worker]
        weights: [0.2, 0.8]