entities:
  project:
    attributes:
      - name: id
        type: integer
        primary_key: true
      - name: name
        type: string
      - name: status
        type: enum
        options: [planning, in_progress, completed]
    generation:
      count: 20

  task:
    attributes:
      - name: id
        type: integer
        primary_key: true
      - name: project_id
        type: integer
        foreign_key: project.id
      - name: name
        type: string
      - name: status
        type: enum
        options: [not_started, in_progress, completed]
    generation:
      count: 100

relationships:
  - from: project
    to: task
    type: one_to_many
    foreign_key: task.project_id

rules:
  - name: update_project_status
    type: update
    target: project
    logic: |
      self.status = 'completed' if all(task.status == 'completed' for task in task) else 'in_progress'