entities:
  - name: Client
    attributes:
      - name: id
        type: int
        primary_key: true
      - name: name
        type: string
        generator:
          type: faker
          method: name
      - name: email
        type: string
        generator:
          type: faker
          method: email

simulation_parameters:
  start_date: "2023-01-01 00:00:00"
  end_date: "2023-02-01 00:00:00"
  time_unit: day

initial_population:
  Client:
    count: 10