name: Build Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: electron/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Python executable
        run: |
          cd python
          python -m PyInstaller main.spec

      - name: Install Node.js dependencies
        run: |
          cd electron
          npm ci

      - name: Build for testing (no packaging)
        run: |
          cd electron
          npm run webpack
        env:
          NODE_ENV: production